config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/projects'
  get 'pages/contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortafolioRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kalam&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/navbars/navbar_principal" %>
  
    <div class="container">
      <%= yield %>
    </div>


    <script src="https://kit.fontawesome.com/8bcc232b0f.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/navbars/_navbar_principal.html.erb
<nav class="navbar navbar-custom navbar-expand-lg" data-bs-theme="dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "Inicio", root_path, class:"nav-link active navbar-brand"  %>
        </li>
        <li class="nav-item">
        <%= link_to "Proyectos", pages_projects_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Contacto", pages_contact_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/pages/contact.html.erb
<h1>~Pagina en construcción~ <br> <i class="fa-solid fa-hammer"></i><i class="fa-solid fa-screwdriver-wrench"></i></h1>
<p>Estamos trabajando para usted~ <br>
Si desea ver información, dirijase y clickee en el apartado "Proyectos" del menú superior</p>

app/views/pages/home.html.erb
<h1>~Pagina en construcción~ <br> <i class="fa-solid fa-hammer"></i><i class="fa-solid fa-screwdriver-wrench"></i></h1>
<p>Estamos trabajando para usted~ <br>
Si desea ver información, dirijase y clickee en el apartado "Proyectos" del menú superior</p>

app/views/pages/projects.html.erb
<h1>Mis Proyectos~</h1>

<div class="container d-flex flex-wrap justify-content-center">
<div class="p-5">
<div class="card" style="width: 18rem;">
  <%= image_tag 'viajes.png' %>
  <div class="card-body cardbody-custom">
    <p class="card-text text-custom">Viajes Chile</p>
    <a href="https://danicalderonm.github.io/ViajesChile/" target="_blank" class="btn btn-custom text-custombtn">Ir a la pagina</a>
  </div>
</div>
</div>
<div class="p-5">
<div class="card" style="width: 18rem;">
  <%= image_tag 'iguana.png' %>
  <div class="card-body cardbody-custom">
    <p class="card-text text-custom">Iguana Page</p>
    <a href="https://danicalderonm.github.io/IguanaPage/" target="_blank" class="btn btn-custom text-custombtn">Ir a la pagina</a>
  </div>
  </div>
</div>
</div>
</div>

<div class="container d-flex flex-wrap justify-content-center">
<div class="p-5">
<div class="card" style="width: 18rem;">
  <%= image_tag 'suricata.png' %>
  <div class="card-body cardbody-custom">
    <p class="card-text text-custom">Suricata</p>
    <a href="https://danicalderonm.github.io/Suricataa/" target="_blank" class="btn btn-custom text-custombtn">Ir a la pagina</a>
  </div>
</div>
</div>

<div class="p-5">
<div class="card" style="width: 18rem;">
  <%= image_tag 'meet.png' %>
  <div class="card-body cardbody-custom">
    <p class="card-text text-custom">Meet & Coffee</p>
    <a href="https://danicalderonm.github.io/Meet-Coffee/" target="_blank" class="btn btn-custom text-custombtn">Ir a la pagina</a>
  </div>
</div>
</div>

<div class="container d-flex flex-wrap justify-content-center">
 <a href="https://github.com/DaniCalderonM" target="_blank" class="btn btn-ver-mas">Ver más</a>
</div>
</div>